### ISSUE TITLE
Add 'middleware' which tracks requestId

### ISSUE THREAD

**Issue by Limess** [Financial-Times/lambda-logger#5]
As lambdas run in a single container which is never concurrently executed, it's safe to add global variables to simplify sharing request context.

As such, we can expose a function which wraps the lambda request handler, sets a global transaction ID, and otherwise leaves the signature unchanged.

e.g.
```js
const middleware = (handler) => (event, ...args) => {
    global.transactionId = event.headers['x-correlation-id'];
    return handler(event, ...args);
};

export default middleware;
```

```js
import {middleware} from 'lambda-logger';

exports.handler = middleware((event, context, done) => {
// do work
});
```

The logger can then consume this global if set.

This could potentially be enabled based on an environment variable set on lambda, a custom variable, or NODE_ENV.

### Reference
[Capturing correlation IDs](http://theburningmonk.com/?s=Correlation+IDs)

**Comment by wheresrhys** [comment]
One for EDO to look at some day
